version: '3.7'

services:
  microservice:
    image: node:latest
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 8001:3000
      - 8080:3000
      - 8200:3000
